nftList = [
  {
    id: "0",
    type: "original",
    name: "SINSU",
    desc: "신수는 NFT 프로젝트 전문 스타트업, 언커먼즈의 첫 번째 오리지널 콘텐츠 IP NFT 프로젝트입니다. 동서양 신화와 전설 속 신수들을 모티브로 한 3,333개의 NFT를 청룡개전, 백호개전, 주작개전, 현무개전의 플레이 모드를 통해 온체인으로 육성하고 성장시키는 것이 프로젝트의 핵심입니다.",
    profile: "sinsu_profile.jpg",
    banner: "sinsu_banner.jpg",
    network: "폴리곤",
    scan: "https://polygonscan.com",
    contract: "0x62B645c1ea2315e99182823CEb4406865b2Ca7e4",
    web: "https://sinsu.world",
    community: "https://discord.gg/uhASzSS3Gh",
    sns: "https://twitter.com/sinsuworld",
    marketplace: "https://opensea.io/collection/sinsu",
  },
  {
    id: "1",
    type: "partner",
    name: "DONICAT",
    desc: "도니캣은 주식회사 워크도니의 PFP NFT 프로젝트입니다. 1963년 최초로 우주로 간 고양이 팰리세트를 모티브로 하였으며, NFT 홀더들에게 상업적 IP 활동, 추가적으로 발행되는 후속 NFT 에어드랍, 데일리 토큰 리워드, DAO, 한정 굿즈 구매, 각종 이벤트 참여 등의 혜택을 제공합니다.",
    profile: "donicat_profile.jpg",
    banner: "donicat_banner.jpg",
    network: "폴리곤",
    scan: "https://polygonscan.com",
    contract: "0xAAd2bE499c9E1A3cb618c4E2371422152e7D8FA9",
    web: "http://donicat.com",
    community: "TBA",
    sns: "TBA",
    marketplace: "https://opensea.io/collection/donicat-collection",
  },
  {
    id: "2",
    type: "partner",
    name: "HIDEOUT",
    desc: "하이드아웃은 Web3.0에서 힙하고 반항적이며 자유로운 커뮤니티를 지향하는 PFP NFT 프로젝트입니다. 코어팀에서 Top-down 방식의 로드맵을 제시하지 않고, NFT 홀더들과의 지속적인 소통을 통해 향후 프로젝트의 방향성을 구체화하는 것이 특징적입니다.",
    profile: "hideout_profile.jpg",
    banner: "hideout_banner.jpg",
    network: "이더리움",
    scan: "https://etherscan.io",
    contract: "0xE96E0D27A5Bf9606e2cD32521650E9aE3e395c2a",
    web: "https://hideout.cool/",
    community: "https://open.kakao.com/o/g8f9FB1e",
    sns: "https://twitter.com/hideout_web3",
    marketplace: "https://opensea.io/collection/hideout-web3",
  },
  {
    id: "3",
    type: "partner",
    name: "GANGCHI UNION",
    desc: "강치유니언은 주식회사 라카이코리아에서 독도 강치 부활의 염원을 담은 PFP NFT 프로젝트입니다. 강치유니언 브랜드 제품을 기획 및 제작, 유통하여 매출을 발생시키고, 해당 매출을 NFT 홀더들과 쉐어하며 다양한 기부 및 후원 등 사회 참여 활동에 기여하는 것이 프로젝트의 목표입니다.",
    profile: "gangchiunion_profile.jpg",
    banner: "gangchiunion_banner.jpg",
    network: "폴리곤",
    scan: "https://polygonscan.com",
    contract: "0x472b4D8F0D9d28E88B8B9D5d0791815BCdBdb105",
    web: "https://www.gangchiunion.com",
    community: "https://discord.gg/XU4nXtPU6e",
    sns: "https://twitter.com/GANGCHI_UNION",
    marketplace: "https://opensea.io/collection/gangchi-union-v1",
  },
  {
    id: "4",
    type: "partner",
    name: "MAON : Ondori",
    desc: "마온(마음의 온도)은 멀티테라피 멘탈 헬스케어의 독자적인 컨텐츠를 가진 주식회사 모두좋아진다의 PFP NFT 프로젝트입니다. NFT 홀더는 멀티테라피 모바일 어플리케이션을 통해서 힐링을 하고, 일정 시간이 지나면 리워드를 수령하는 Healing to Earn(H2E)이 가능합니다.",
    profile: "ondori_profile.jpg",
    banner: "ondori_banner.jpg",
    network: "이더리움",
    scan: "https://etherscan.io",
    contract: "0x1361390F4fE093E396ef9B4076117F41Cb45210A",
    web: "https://www.themaon.com",
    community: "http://discord.gg/themaon",
    sns: "https://twitter.com/The_Maon",
    marketplace: "https://opensea.io/collection/maon-ondori",
  },
  {
    id: "5",
    type: "partner",
    name: "GENESIS CORE",
    desc: "제네시스 코어는 10,000개의 픽셀 아트 기반 PFP NFT 프로젝트입니다. 코어팀이 가지고 있는 영상 콘텐츠 및 바이럴 콘텐츠 제작 역량을 바탕으로 '헬로키티'와 같은 글로벌 콘텐츠 IP 브랜드가 되는 것이 프로젝트의 궁극적인 목표입니다.",
    profile: "genesiscore_profile.jpg",
    banner: "genesiscore_banner.jpg",
    network: "이더리움",
    scan: "https://etherscan.io",
    contract: "TBA",
    web: "https://genesiscore.io",
    community: "https://discord.gg/Y33v9frKFT",
    sns: "https://twitter.com/GenesisCoreNFT",
    marketplace: "TBA",
  },
  {
    id: "6",
    type: "partner",
    name: "Louis Cats NAVi",
    desc: "루이스 캣츠 나비는 영국 런던 출신의 화가 루이스 웨인의 고양이 그림을 모티브로 제작된 PFP NFT 프로젝트입니다. 현대백화점 무역센터점에서 루이스웨인 전시전을 성공적으로 마쳤으며, 이후 다양한 방송 콘텐츠 및 전시, 공연 등과의 협업을 진행할 예정입니다.",
    profile: "louiscats_profile.jpg",
    banner: "louiscats_banner.jpg",
    network: "클레이튼",
    scan: "https://scope.klaytn.com",
    contract: "0xeadbb5be5a5952108443296263df27a99d768ae1",
    web: "http://louiscat.art",
    community: "https://discord.gg/b9e3ftXSsH",
    sns: "https://twitter.com/Louisnavi",
    marketplace: "https://opensea.io/collection/louiscats-xsp6nrgkci",
  },
  {
    id: "7",
    type: "curated",
    name: "Bored Ape Yacht Club",
    desc: "BAYC(Bored Ape Yacht Club)는 블록체인 스타트업 유가랩스(Yaga labs)가 2021년 4월 발행한 NFT 프로젝트입니다. BAYC NFT 컬렉션에는 지루해 하는 표정을 짓고 있는 원숭이가 프로필 사진을 찍은 듯이 그려져 있습니다. 배경색을 포함하여 모자, 눈, 의상 등 170가지 다른 특성의 맞춤형 생성 알고리즘으로 원숭이에 희소성을 부여하여 각각의 캐릭터들은 고유한 특징을 지니고 있습니다.",
    profile: "bayc_profile.png",
    banner: "bayc_banner.jpg",
    network: "이더리움",
    scan: "https://etherscan.io",
    contract: "0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D",
    web: "https://boredapeyachtclub.com",
    community: "https://discord.gg/3P5K3dzgdB",
    sns: "https://twitter.com/BoredApeYC",
    marketplace: "https://opensea.io/collection/boredapeyachtclub",
  },
  {
    id: "8",
    type: "curated",
    name: "Azuki",
    desc: "아즈키(Azuki)는 2022년 1월 미국 로스앤젤레스 기반 아티스트 그룹인 치루랩스(Chiru Labs)에서 출시한 PFP NFT 프로젝트입니다. 마치 일본 애니메이션 캐릭터 같은 독특한 화풍으로 NFT 시장에서 높은 거래량을 보여 주고 있습니다.",
    profile: "azuki_profile.jpg",
    banner: "azuki_banner.jpeg",
    network: "이더리움",
    scan: "https://etherscan.io",
    contract: "0xED5AF388653567Af2F388E6224dC7C4b3241C544",
    web: "https://www.azuki.com/",
    community: "http://discord.gg/azuki",
    sns: "https://twitter.com/azukiofficial",
    marketplace: "https://opensea.io/collection/azuki",
  },
  {
    id: "9",
    type: "curated",
    name: "BEANZ",
    desc: "빈즈(BEANZ)는 2022년 4월 출시된 치루랩스(Chiru Labs)의 아즈키(Azuki) 확장판 NFT 프로젝트입니다. 빈즈는 '아즈키 여정의 조수'라는 콘셉트로 아즈키 NFT 소유자에게는 에어드랍을 통해 1인당 2개씩 무료로 제공되었습니다. 이렇게 추가된 2만여개의 빈즈는 아즈키 생태계로의 진입 장벽을 낮추며, 기존 홀더들에게는 부가적인 수익원으로서의 역할을 하였습니다.",
    profile: "beanz_profile.jpg",
    banner: "beanz_banner.jpg",
    network: "이더리움",
    scan: "https://etherscan.io",
    contract: "0x306b1ea3ecdf94aB739F1910bbda052Ed4A9f949",
    web: "https://www.azuki.com/beanz",
    community: "http://discord.gg/azuki",
    sns: "https://twitter.com/azukiofficial",
    marketplace: "https://opensea.io/collection/beanzofficial",
  },
];
